# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-14 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shorturl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curl', models.URLField(verbose_name='长连接')),
                ('durl', models.CharField(max_length=10, unique=True, verbose_name='短连接')),
                ('number', models.IntegerField(default=0, verbose_name='计数')),
            ],
        ),
    ]
